variable "ssh_provisioner_user" {}
variable "ssh_provisioner_password" {}
variable "char_array" {}
variable "vsphere_password" {}
variable "vsphere_user" {}
variable "vsphere_endpoint" {}
variable "vsphere_datacenter" {}
variable "vsphere_datastore" {}
variable "vsphere_resource_pool" {}
variable "vsphere_network" {}
variable "vsphere_virtual_template" {}
variable "vsphere_vm_name_prefix" {}
variable "vsphere_vm_num_cpus" {}
variable "vsphere_vm_num_mem" {}
variable "vsphere_vm_subnet" {}
variable "vsphere_vm_subnet_offset" {}
variable "vsphere_vm_gateway" {}
